### ISSUE TITLE
ImportError: cannot import name 'badgerfish' 

### ISSUE THREAD

**Issue by PyPatel** [sanand0/xmljson#31] opened 2018-03-28 07:41 UTC
Traceback (most recent call last):
      File "D:\Codes\TPN\xmljson.py", line 1, in
        from xmljson import badgerfish as bf
      File "D:\Codes\TPN\xmljson.py", line 1, in
        from xmljson import badgerfish as bf
    ImportError: cannot import name 'badgerfish'

I am using `Python 3.6`

**Comment by dpalharini** [comment] 2018-05-18 04:07
I am having the same problem.

Python 2.7.
Ubuntu 16.04.

**Comment by mukultaneja** [comment] 2018-05-18 06:00
I have tried xmljson (v0.1.9) with Python 3.6.3 and Python 2.7.5 but not able to reproduce the error. Can you please check for the latest versions or share more trace so that I can reproduce the error?

<img width="1679" alt="screen shot 2018-05-18 at 11 28 38 am" src="https://user-images.githubusercontent.com/16931639/40218442-df24fe84-5a8e-11e8-9610-e1e0c179c0f1.png">
<img width="1679" alt="screen shot 2018-05-18 at 11 29 19 am" src="https://user-images.githubusercontent.com/16931639/40218443-df5159fc-5a8e-11e8-9573-74ac007a4688.png">

**Comment by dpalharini** [comment] 2018-05-19 02:38
I use Python 2.7.12.

![image](https://user-images.githubusercontent.com/5911360/40264147-34dc411a-5af4-11e8-8a5c-ea0360fc0174.png)

![image](https://user-images.githubusercontent.com/5911360/40264154-5b85ed20-5af4-11e8-90a4-701a862e94d6.png)

The package was installed and it has been found, but the item inside the package does not exist!

What can I do to provide more information?

**Comment by mukultaneja** [comment] 2018-05-19 08:28
@dpalharini I am still not able to reproduce the error. This time I tried with Ubuntu 16.04 and Python 2.7.12.

<img width="1680" alt="screen shot 2018-05-19 at 1 57 40 pm" src="https://user-images.githubusercontent.com/16931639/40266627-a4a25502-5b6c-11e8-8314-a6e2bf1cb477.png">

<img width="1675" alt="screen shot 2018-05-19 at 1 46 52 pm" src="https://user-images.githubusercontent.com/16931639/40266568-7818ee16-5b6b-11e8-9cfc-034aa782098d.png">

<img width="1680" alt="screen shot 2018-05-19 at 1 47 07 pm" src="https://user-images.githubusercontent.com/16931639/40266569-78428618-5b6b-11e8-904e-aedc12079881.png">

As I can see your 'pip show' output, it seems you are not getting any data from the package. I think you should check once `/usr/local/lib/python2.7/dist-packages/xmljson/__init__.py` for the content or can try to reinstall the package using `pip install https://github.com/sanand0/xmljson/archive/master.zip`

Hope it will help!

**Comment by sanand0** [comment] 2018-11-21 17:23
Closing this issue for now since we aren't able to reproduce it.

For future reference, if anyone can share an environment where they're able to reproduce it, we can try and debug it.

**Closed as completed by sanand0** 2018-11-21 17:23 UTC

**Comment by pfriedland** [comment] 2019-02-08 01:43
I'm seeing this same problem on Mac OS High Sierra - both from native Python2 and brew installed Python3.
